# -*-bash-*-
# this file creates all links to files in the data directory needed for
# running the application on a specific machine.
#
# example
# ln -sf $DATADIR/*.cnf .

# standard folder with project-wide data
DATADIR=$(realpath ../../run-data)

# python helper script
ln -sf $DATADIR/which_dueca_gtk.py .
ln -sf ../../../call-python/callpython.py .

# create a folder for run log history
if [ ! -d runlogs ]; then
   mkdir runlogs
fi

ln -sf ${DATADIR}/initials-PHLAB.toml .
ln -sf ../../../build/dueca_run.x .
